//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpticalWire.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpticalWire.Resource.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add intensity on graphic.
        /// </summary>
        internal static string bnAddIntensityOngraphic {
            get {
                return ResourceManager.GetString("bnAddIntensityOngraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply selected filtr.
        /// </summary>
        internal static string bnAppliedFiltr {
            get {
                return ResourceManager.GetString("bnAppliedFiltr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build all angle.
        /// </summary>
        internal static string bnBuildAllDiametr {
            get {
                return ResourceManager.GetString("bnBuildAllDiametr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build all angle.
        /// </summary>
        internal static string bnBuildAllInfluence {
            get {
                return ResourceManager.GetString("bnBuildAllInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build all angle.
        /// </summary>
        internal static string bnBuildAllintensity {
            get {
                return ResourceManager.GetString("bnBuildAllintensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build select.
        /// </summary>
        internal static string bnBuildDiametr {
            get {
                return ResourceManager.GetString("bnBuildDiametr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build select.
        /// </summary>
        internal static string bnBuildintensity {
            get {
                return ResourceManager.GetString("bnBuildintensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build select.
        /// </summary>
        internal static string bnBuildSelectinfluence {
            get {
                return ResourceManager.GetString("bnBuildSelectinfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string bnClear {
            get {
                return ResourceManager.GetString("bnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear graphics.
        /// </summary>
        internal static string bnClearGraphic {
            get {
                return ResourceManager.GetString("bnClearGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw angle on image.
        /// </summary>
        internal static string bnDrawAngle {
            get {
                return ResourceManager.GetString("bnDrawAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string bnHideGraphic {
            get {
                return ResourceManager.GetString("bnHideGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        internal static string bnRemoveAll {
            get {
                return ResourceManager.GetString("bnRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove select graphics.
        /// </summary>
        internal static string bnRemoveFromgraphic {
            get {
                return ResourceManager.GetString("bnRemoveFromgraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string bnShowGraphic {
            get {
                return ResourceManager.GetString("bnShowGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write graphics to excel.
        /// </summary>
        internal static string bnWriteToExcel {
            get {
                return ResourceManager.GetString("bnWriteToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string chb0 {
            get {
                return ResourceManager.GetString("chb0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        internal static string chb45 {
            get {
                return ResourceManager.GetString("chb45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        internal static string chb90 {
            get {
                return ResourceManager.GetString("chb90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should normalize value?.
        /// </summary>
        internal static string chBShouldNormalise {
            get {
                return ResourceManager.GetString("chBShouldNormalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APSCOS - Main windows.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build diametr.
        /// </summary>
        internal static string gbBuildDiametr {
            get {
                return ResourceManager.GetString("gbBuildDiametr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrs.
        /// </summary>
        internal static string gbFiltrs {
            get {
                return ResourceManager.GetString("gbFiltrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build intensity.
        /// </summary>
        internal static string gbIntensity {
            get {
                return ResourceManager.GetString("gbIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity at angle.
        /// </summary>
        internal static string gbIntensityAngle {
            get {
                return ResourceManager.GetString("gbIntensityAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters of graphics.
        /// </summary>
        internal static string gbParametersofGraphics {
            get {
                return ResourceManager.GetString("gbParametersofGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influence by temperature.
        /// </summary>
        internal static string gbTemperatureInfluense {
            get {
                return ResourceManager.GetString("gbTemperatureInfluense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle with max diametr.
        /// </summary>
        internal static string lbAnglemaxDiametr {
            get {
                return ResourceManager.GetString("lbAnglemaxDiametr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assimetry.
        /// </summary>
        internal static string lbAssim {
            get {
                return ResourceManager.GetString("lbAssim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n2.
        /// </summary>
        internal static string lbCoefficienIn {
            get {
                return ResourceManager.GetString("lbCoefficienIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n1.
        /// </summary>
        internal static string lbCoefficienOut {
            get {
                return ResourceManager.GetString("lbCoefficienOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diametr.
        /// </summary>
        internal static string lbDiam {
            get {
                return ResourceManager.GetString("lbDiam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lbDiametr {
            get {
                return ResourceManager.GetString("lbDiametr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess.
        /// </summary>
        internal static string lbExc {
            get {
                return ResourceManager.GetString("lbExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select filtr.
        /// </summary>
        internal static string lbFiltrName {
            get {
                return ResourceManager.GetString("lbFiltrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free angle.
        /// </summary>
        internal static string lbFreeAngle {
            get {
                return ResourceManager.GetString("lbFreeAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lbFromDiametr {
            get {
                return ResourceManager.GetString("lbFromDiametr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lbFrominfluence {
            get {
                return ResourceManager.GetString("lbFrominfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lbFromIntensity {
            get {
                return ResourceManager.GetString("lbFromIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main angle.
        /// </summary>
        internal static string lbMainAngle {
            get {
                return ResourceManager.GetString("lbMainAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max diametr.
        /// </summary>
        internal static string lbMaxDiametr {
            get {
                return ResourceManager.GetString("lbMaxDiametr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max intensity.
        /// </summary>
        internal static string lbMaxintensity {
            get {
                return ResourceManager.GetString("lbMaxintensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select graphics.
        /// </summary>
        internal static string lbSelectGraph {
            get {
                return ResourceManager.GetString("lbSelectGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select graphics.
        /// </summary>
        internal static string lbSelectGraphic {
            get {
                return ResourceManager.GetString("lbSelectGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lbToInfluence {
            get {
                return ResourceManager.GetString("lbToInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lbTointensity {
            get {
                return ResourceManager.GetString("lbTointensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall width.
        /// </summary>
        internal static string lbWidthWall {
            get {
                return ResourceManager.GetString("lbWidthWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influence diametrs of PCF by angle.
        /// </summary>
        internal static string ZGDiametrTop {
            get {
                return ResourceManager.GetString("ZGDiametrTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle of rotation, grad.
        /// </summary>
        internal static string ZGDiametrX {
            get {
                return ResourceManager.GetString("ZGDiametrX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize diamert PCF.
        /// </summary>
        internal static string ZGDiametrY {
            get {
                return ResourceManager.GetString("ZGDiametrY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity of distribution PCF.
        /// </summary>
        internal static string ZGintencityTop {
            get {
                return ResourceManager.GetString("ZGintencityTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string ZGintencityX {
            get {
                return ResourceManager.GetString("ZGintencityX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized intensity of distribution.
        /// </summary>
        internal static string ZGintencityY {
            get {
                return ResourceManager.GetString("ZGintencityY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influense from temperature.
        /// </summary>
        internal static string ZGTemperatureTopic {
            get {
                return ResourceManager.GetString("ZGTemperatureTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T, C grad.
        /// </summary>
        internal static string ZGTemperatureX {
            get {
                return ResourceManager.GetString("ZGTemperatureX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to λ ,nm.
        /// </summary>
        internal static string ZGTemperatureY {
            get {
                return ResourceManager.GetString("ZGTemperatureY", resourceCulture);
            }
        }
    }
}
